export const datenschutz = {
  hero: {
    headline: "Datenschutz",
    subline: "Informationen zur Verarbeitung personenbezogener Daten auf dieser Website gemäß Art. 13 DSGVO.",
  },
  hinweis: "Diese Datenschutzerklärung ist ein erster Entwurf und muss vor Live-Schaltung der Website durch einen Anwalt oder Datenschutzbeauftragten geprüft werden.",
  sections: [
    { title: "1. Verantwortlicher", body: ["Verantwortlich für die Datenverarbeitung auf dieser Website ist:", "V.I.B. Voß Immobilien Beratung", "Edith Voß", "Alte Schulstraße 28, 68549 Ilvesheim", "Telefon: +49 173 360 19 36", "E-Mail: info@e-vib.de"] },
    { title: "2. Erhebung allgemeiner Informationen", body: ["Beim Aufruf dieser Website werden automatisch Informationen technischer Natur erhoben (z.B. Browsertyp, Betriebssystem, IP-Adresse, Zugriffszeit). Diese Daten werden ausschließlich zur Sicherstellung des reibungslosen Betriebs der Seite verarbeitet und nach kurzer Zeit gelöscht. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO."] },
    { title: "3. Kontaktformular und Suchprofil", body: ["Wenn Sie mich über das Kontaktformular oder das Suchprofil-Formular kontaktieren, werden Ihre Angaben (Name, E-Mail, Telefon, Nachricht, Suchkriterien) zur Bearbeitung Ihrer Anfrage und für mögliche Anschlussfragen gespeichert. Eine Weitergabe an Dritte erfolgt nicht.", "Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO (Vertragsanbahnung) oder Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse).", "Speicherdauer: Bis zum Abschluss des Vorgangs bzw. solange für die Beratung erforderlich. Spätestens nach 3 Jahren erfolgt eine Prüfung auf Löschung."] },
    { title: "4. Cookies", body: ["Diese Website setzt nur technisch notwendige Cookies ein. Tracking-Cookies oder Drittanbieter-Cookies werden nicht verwendet."] },
    { title: "5. E-Mail-Versand des Kontaktformulars", body: ["Wenn Sie das Kontaktformular absenden, werden Ihre Eingaben verschlüsselt (HTTPS) an eine Serverless-Funktion der Hosting-Plattform übertragen und von dort als E-Mail an mein Postfach (info@e-vib.de) zugestellt. Für den E-Mail-Versand wird der Dienst Resend (Resend, Inc., USA) als Auftragsverarbeiter eingesetzt.", "Verarbeitet werden dabei die von Ihnen eingegebenen Daten (Name, E-Mail, Telefon, Nachricht). Eine darüber hinausgehende Speicherung bei Resend erfolgt nur im Rahmen der technischen Zustellung.", "Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO (Vertragsanbahnung) bzw. Art. 6 Abs. 1 lit. f DSGVO. Mit Resend besteht ein Auftragsverarbeitungsvertrag (AVV). Da eine Übermittlung in die USA stattfinden kann, wird diese durch geeignete Garantien (EU-US Data Privacy Framework bzw. Standardvertragsklauseln) abgesichert."] },
    { title: "6. Hosting", body: ["Diese Website wird bei Vercel Inc. (USA) gehostet. Beim Aufruf der Seite verarbeitet Vercel technisch notwendige Daten (u.a. IP-Adresse, Zeitpunkt des Zugriffs, abgerufene Ressource sowie Browser- und Geräteinformationen) in Server-Logfiles, um die Auslieferung und Sicherheit der Website zu gewährleisten.", "Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an einem sicheren und stabilen Betrieb). Mit Vercel besteht ein Auftragsverarbeitungsvertrag (AVV); eine etwaige Datenübermittlung in die USA wird durch geeignete Garantien (EU-US Data Privacy Framework bzw. Standardvertragsklauseln) abgesichert."] },
    { title: "7. Schriftarten", body: ["Die Schriftarten Manrope und Playfair Display werden selbst gehostet (über Next.js Font Optimization) und nicht von externen CDNs nachgeladen. Es findet kein Drittland-Transfer zur Schriftauslieferung statt."] },
    { title: "8. Ihre Rechte", body: ["Sie haben das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Für die Geltendmachung wenden Sie sich an info@e-vib.de.", "Außerdem haben Sie das Recht auf Beschwerde bei einer Datenschutzaufsichtsbehörde."] },
  ],
} as const;
