export const home = {
  hero: {
    eyebrow: "V.I.B. Voß Immobilien Beratung",
    headline: "Verkaufen aus Leidenschaft.",
    subline:
      "Seit 30 Jahren bin ich mit Leidenschaft und Herzblut als selbstständige Immobilienmaklerin tätig, regional verwurzelt in der Rhein-Neckar-Region, im Raum Karlsruhe, dem vorderen Odenwald und Rheinland-Pfalz, sowie überregional.",
    primaryCta: { label: "Mit mir sprechen", href: "#kontakt" },
    secondaryCta: { label: "Über mich", href: "#ueber-mich" },
    trustStrip: ["30 Jahre Erfahrung", "Rhein-Neckar & überregional", "Off-Market-Netzwerk"],
  },
  intro: {
    body: [
      "Mir geht es nicht darum, die typischen Eigenschaften aufzuzählen, die die meisten Makler nennen — Diskretion, Vertrauen, beste Wertermittlung.",
      "Mein Schwerpunkt sind drei Dinge: mein Gespür für die beste Verkaufsmöglichkeit, mein weit über die Grenzen hinausgehendes Netzwerk und das professionelle Auftreten sowie der persönliche Umgang mit Käufer und Verkäufer.",
    ],
  },
  usps: [
    {
      icon: "diamond",
      title: "Gespür für die beste Verkaufsmöglichkeit",
      body: "Aufgrund meiner langjährigen Tätigkeit berate ich Sie realistisch, präzise und fundiert — ohne die gängigen Online-Wertermittlungen wie ImmoScout, Sprengnetter und andere.",
    },
    {
      icon: "hub",
      title: "Mein Netzwerk wirkt vor der Veröffentlichung",
      body: "Als die etwas andere Maklerin liegt meine Stärke darin, ein Objekt zu sehen und vor Veröffentlichung passende Käufer aus meinem Kundenstamm zu kontaktieren. Für viele meiner Verkäufer und Kunden bin ich seit Jahren Ansprechpartner.",
    },
    {
      icon: "person",
      title: "Professionelles Auftreten, persönlicher Umgang",
      body: "Ein kleines, sehr angesehenes Maklerbüro — transparent, unbürokratisch, auch am Wochenende erreichbar.",
      href: "#aktuelle-immobilien",
      hrefLabel: "Aktuelle Immobilien ansehen",
    },
  ],
  ueberMich: {
    eyebrow: "Über mich",
    headline: "Edith Voss",
    paragraphs: [
      "Seit 30 Jahren bin ich mit Leidenschaft und Herzblut als selbstständige Immobilienmaklerin tätig, regional verwurzelt in der Rhein-Neckar-Region, im Raum Karlsruhe, dem vorderen Odenwald und Rheinland-Pfalz, sowie überregional.",
      "Nach einem Fremdsprachenstudium in Frankfurt arbeitete ich für ein internationales Textilhandelsunternehmen und war viele Jahre als Geschäftsführerin und Mitinhaberin in Fernost, New York, Istanbul und Indien tätig. 1996 wechselte ich in die Immobilienbranche und baute mit Edith Voss Immobilien eines der erfolgreichsten Maklerbüros im Rhein-Neckarkreis auf.",
      "Mein Unternehmen Edith Voss Immobilien in Weinheim habe ich mit viel Fleiß und Freude am Makeln zu einem der etabliertesten Maklerbüros geführt und 2015 verkauft, mein Name ist noch heute das Aushängeschild der Firma, die weiter erfolgreich geführt wird. Nach längeren Auslandsaufenthalten, unter anderem in Südafrika, kehrte ich mit frischer Energie zurück. Familie, Freunde und die Geburt meines Enkelkindes machten schnell klar: Mein Platz ist hier, an der Bergstraße.",
      "Da der alte Name rechtlich gebunden war, gründete ich meine neue Marke: V.I.B. Voß Immobilien Beratung. Meinen Namen habe ich abgegeben, aber nicht meine Haltung. Ich bin und bleibe das Original: mit Herz, Erfahrung und der Leidenschaft, Menschen und Immobilien zusammenzubringen.",
      "Meine Philosophie: „Verkaufen aus Leidenschaft.“ Mein Motto, nach Heraklit von Ephesus: „Nichts ist so beständig wie der Wandel.“ Ein Kunde schrieb mir nach erfolgreichem Verkauf, dass ich das Negativ-Image meines Berufsstandes eindrucksvoll widerlege. Darauf bin ich stolz.",
    ],
  },
  leistungen: {
    eyebrow: "Was ich für Sie tue",
    headline: "Vom ersten Gespräch bis zur Beurkundung",
    items: [
      "Fundierte Wertberatung — realistisch, präzise, persönlich",
      "Off-Market-Vermarktung über meinen langjährigen Kundenstamm",
      "Beschaffung objektbezogener Unterlagen — bei Bedarf direkt mit den Ämtern",
      "Professionelles Exposé mit optimaler Darstellung",
      "Verhandlungen mit potenziellen Kaufinteressenten",
      "Klärung der Finanzierung",
      "Begleitung bis zur notariellen Beurkundung",
      "Erreichbarkeit auch am Wochenende",
    ],
  },
  immobilien: {
    eyebrow: "Immobilien",
    headline: "Aktuelle Immobilien vermittle ich diskret.",
    body: [
      "Bereits vor der offiziellen Vermarktung greife ich auf meinen gewachsenen, solventen Kundenstamm zurück. Oft entstehen erfolgreiche Verkäufe schon durch gezielte persönliche Kontakte — diskret und ohne öffentliche Vermarktung.",
      "Wenn Sie suchen oder verkaufen möchten, sprechen Sie mich direkt an.",
    ],
    schwerpunkt:
      "Schwerpunkt: exklusive Villen und Mehrfamilienhäuser, aber auch gemütliche Einfamilienhäuser, Wohnungen oder das kleine Apartment mitten in der Stadt.",
    ctaVerkauf: { label: "Immobilie verkaufen", href: "#kontakt" },
    ctaKauf: { label: "Suchprofil hinterlegen", href: "#kontakt" },
    items: [
      {
        slug: "juwel-bergstrasse",
        titel: "Juwel an der Bergstraße — Exklusive Villa in Panorama-Lage",
        untertitel: "Exklusive Villa in traumhafter Panorama-Lage",
        ort: "69469 Weinheim",
        image: "/images/referenzen/gal-juwel-01-1600.jpg",
        bilder: [
          "/images/referenzen/gal-juwel-01-1600.jpg",
          "/images/referenzen/gal-juwel-02-1600.jpg",
          "/images/referenzen/gal-juwel-03-1600.jpg",
          "/images/referenzen/gal-juwel-04-1600.jpg",
          "/images/referenzen/gal-juwel-05-1600.jpg",
          "/images/referenzen/gal-juwel-06-1600.jpg",
          "/images/referenzen/gal-juwel-07-1600.jpg",
          "/images/referenzen/gal-juwel-08-1600.jpg",
          "/images/referenzen/gal-juwel-09-1600.jpg",
          "/images/referenzen/gal-juwel-10-1600.jpg",
          "/images/referenzen/gal-juwel-11-1600.jpg",
          "/images/referenzen/gal-juwel-12-1600.jpg",
          "/images/referenzen/gal-juwel-13-1600.jpg",
          "/images/referenzen/gal-juwel-14-1600.jpg",
          "/images/referenzen/gal-juwel-15-1600.jpg",
          "/images/referenzen/gal-juwel-16-1600.jpg",
        ],
        preis: "auf Anfrage",
        eckdaten: {
          wohnflaeche: "ca. 515 m²",
          grundstueck: "ca. 2.069 m²",
          nutzflaeche: "ca. 93 m²",
          zimmer: 10,
          schlafzimmer: 6,
          badezimmer: 4,
          balkonTerrasse: 1,
          stellplaetze: 4,
        },
        bauinfo: {
          baujahr: 1970,
          letzteModernisierung: 2022,
          zustand: "vollständig renoviert",
          energieausweis: "bei Besichtigung",
          primaerenergie: "Öl",
          heizung: "Zentralheizung",
        },
        verfuegbar: "nach Vereinbarung",
        beschreibung: [
          "Hoch über Weinheim, eingebettet in eine der begehrtesten Lagen der Bergstraße, erwartet Sie eine außergewöhnliche Villa mit spektakulärem Panoramablick über die Rheinebene. Von hier aus schweift der Blick über Weinheim, Mannheim, Heidelberg, die Pfalz, die Vogesen bis hin zum Schwarzwald — ein Ausblick, der jeden Tag aufs Neue fasziniert. Das uneinsehbare Anwesen liegt in einer privaten Anliegerstraße und bietet absolute Ruhe, Privatsphäre und Sicherheit. Direkt hinter dem Grundstück beginnt ein weitläufiges Landschaftsschutzgebiet — Natur, Weite und Freiheit verbinden sich hier zu einem einzigartigen Lebensgefühl.",
          "Die Villa überzeugt mit großzügigen, lichtdurchfluteten Wohnräumen und bodentiefen Panoramafenstern, die den Blick über die Landschaft inszenieren wie ein lebendiges Gemälde. Repräsentative Wohnbereiche, ein Kaminzimmer mit Feuerplatz sowie mehrere Terrassen und Sonnenloggien schaffen ideale Voraussetzungen für stilvolle Empfänge oder entspannte Stunden im privaten Kreis.",
          "Hochwertige Materialien wie Travertinböden, edle Massivhölzer, maßgefertigte Schreinerarbeiten sowie ausgewählte Wand- und Deckenleuchten unterstreichen den repräsentativen Charakter der Immobilie. Die großzügige Küche ist mit hochwertigen Geräten von Miele und Gaggenau ausgestattet und überzeugt durch ihre klare Gestaltung, viel Arbeitsfläche und helle Fensterbereiche, die den Raum mit Tageslicht erfüllen.",
          "Eine separate Einliegerwohnung mit eigenem Zugang bietet vielseitige Nutzungsmöglichkeiten — ideal für Gäste, Familienmitglieder, Personal oder als repräsentativer Arbeitsbereich.",
          "Ob als großzügiges Familienanwesen, als repräsentativer Wohnsitz oder als Rückzugsort mit außergewöhnlicher Lebensqualität — diese Immobilie vereint Privatsphäre, Natur und Panorama in einer Form, die in Weinheim nur selten zu finden ist.",
        ],
        lage:
          "Weinheim ist eine beliebte Stadt an der idyllischen Bergstraße mit mediteranem Flair, der romantischen Altstadt, dem wunderschönen Marktplatz sowie dem Wahrzeichen Weinheims — die 2 Burgen. Die Region ist äußerst beliebt und sehr gefragt. Highlights sind der bekannte Exotenwald, der malerische Schlosspark und der weit über die Grenzen hinaus bekannte Hermannshof. Die Kreisklinik bietet beste medizinische Versorgung. Die Stadt ist mit ihren ca. 49.000 Einwohnern und dem Sitz namhafter Unternehmen Mittelzentrum in der prosperierenden Metropolregion Rhein-Neckar mit ca. 2,3 Mio. Einwohnern. Durch die sehr gute Anbindung an A 5, A 6, A 61, A 65 und an den ÖPNV (DB ICE + IC) erreichen Sie in kürzester Zeit die umliegenden Städte Mannheim, Heidelberg, Darmstadt, Frankfurt und den internationalen Frankfurter Flughafen. Weltbekannte Universitäten in Heidelberg, Mannheim, Darmstadt und Frankfurt und viele renommierte Universitätskliniken mit allen Fakultäten befinden sich in direkter Nachbarschaft.",
        ausstattung: [
          "Balkon",
          "Gehobene Ausstattung",
          "Dusche",
          "Bad mit Badewanne",
          "Bad mit Fenster",
          "Einbauküche",
          "Fliesen",
          "Stein",
          "Parkett",
          "Kamin",
          "Garage",
          "Garten",
          "Sauna",
          "Keller",
          "Gäste-WC",
        ],
      },
      {
        slug: "dachwohnung-rheinebene",
        titel: "Charmante Dachgeschosswohnung mit Blick in die Rheinebene",
        untertitel: "Exklusive Eigentumswohnung in bester, gesuchter Lage Weinheim",
        ort: "69469 Weinheim",
        image: "/images/referenzen/gal-dachwohnung-01-1600.jpg",
        bilder: [
          "/images/referenzen/gal-dachwohnung-01-1600.jpg",
          "/images/referenzen/gal-dachwohnung-02-1600.jpg",
          "/images/referenzen/gal-dachwohnung-03-1600.jpg",
          "/images/referenzen/gal-dachwohnung-04-1600.jpg",
          "/images/referenzen/gal-dachwohnung-05-1600.jpg",
          "/images/referenzen/gal-dachwohnung-06-1600.jpg",
          "/images/referenzen/gal-dachwohnung-07-1600.jpg",
          "/images/referenzen/gal-dachwohnung-08-1600.jpg",
          "/images/referenzen/gal-dachwohnung-09-1600.jpg",
          "/images/referenzen/gal-dachwohnung-10-1600.jpg",
          "/images/referenzen/gal-dachwohnung-11-1600.jpg",
          "/images/referenzen/gal-dachwohnung-12-1600.jpg",
        ],
        preis: "650.000 €",
        eckdaten: {
          wohnflaeche: "ca. 105 m²",
          nutzflaeche: "ca. 40 m²",
          zimmer: 4,
          schlafzimmer: 3,
          badezimmer: 2,
          balkonTerrasse: 2,
          stellplaetze: 4,
        },
        bauinfo: {
          baujahr: 1993,
          zustand: "renoviert",
          energieausweis: "Verbrauchsausweis, Klasse E, gültig bis 13.02.2029",
          primaerenergie: "Gas",
          heizung: "Zentralheizung",
        },
        verfuegbar: "nach Vereinbarung",
        beschreibung: [
          "Die großzügige Dachgeschosswohnung befindet sich in einem sehr gepflegten Vier-Parteienhaus in begehrter, zentrumsnaher Wohnlage mit hoher Wohn- und Lebensqualität.",
          "Die Wohnfläche verteilt sich auf vier Räume: ein großzügiges Wohn- und Esszimmer mit bodentiefen Fenstern und beeindruckendem Blick in die Rheinebene, zwei Schlafzimmer sowie ein flexibel nutzbares Arbeits- oder Gästezimmer. Zwei Balkone erweitern den Wohnraum ins Freie: ein großer Ostbalkon als geschützte Rückzugsoase sowie ein sonniger Südbalkon mit weitem Ausblick.",
          "Das helle Tageslichtbad ist mit Badewanne sowie einer hochwertigen, multifunktionalen Duschkabine mit integrierter Wellnessfunktion ausgestattet. Ergänzt wird das Raumangebot durch ein weiteres Duschbad. Die separate Einbauküche verfügt über alle gängigen Markengeräte und fügt sich funktional in das Gesamtbild der Wohnung ein.",
          "Für ein angenehmes Wohnklima sorgt die durchgehend vorhandene Fußbodenheizung. Hochwertiges Parkett unterstreicht den behaglichen Charakter der Räume. Zur Wohnung gehören ein separater Kellerraum sowie eine Doppelgarage und vier Stellplätze.",
          "Hinweis: Die Gesamtfläche der Wohnung beträgt ca. 131 m². Aufgrund der Dachschrägen werden hiervon ca. 105 m² als anrechenbare Wohnfläche zugrunde gelegt.",
        ],
        lage:
          "Die Dachgeschosswohnung befindet sich in bester, gesuchter Wohnlage von Weinheim, einer der gefragtesten Städte an der Badischen Bergstraße. Die Umgebung vereint urbanes Leben mit naturnaher Wohnqualität und zählt zur wirtschaftsstarken Metropolregion Rhein-Neckar. In fußläufiger Entfernung erreichen Sie die charmante Weinheimer Altstadt mit ihrem historischen Marktplatz, zahlreichen Cafés, Restaurants und individuellen Geschäften. Auch der Schlosspark, der Exotenwald sowie vielfältige Freizeit- und Naherholungsmöglichkeiten befinden sich in unmittelbarer Nähe. Die Verkehrsanbindung ist hervorragend: Der Bahnhof Weinheim bietet Anschluss an den Regional- und Fernverkehr, die Straßenbahn entlang der Bergstraße eine schnelle Verbindung nach Heidelberg und Mannheim. Zudem sind die Autobahnen A5 und A659 in wenigen Minuten erreichbar. Weinheim gilt als „Zwei-Burgen-Stadt“ und überzeugt durch seine einzigartige Lage zwischen Odenwald und Rheinebene.",
        ausstattung: [
          "2 Balkone (Ost und Süd)",
          "Doppelgarage",
          "Gehobene Ausstattung",
          "Dusche",
          "Bad mit Badewanne",
          "Bad mit Fenster",
          "Einbauküche",
          "Fußbodenheizung",
          "Fliesen",
          "Parkett",
          "Keller",
          "Abstellraum",
          "Gäste-WC",
        ],
      },
      {
        slug: "villa-rheinebene",
        titel: "Reizvolle Villa in Bestlage mit Blick in die Rheinebene",
        untertitel: "Großzügiges Villenanwesen in privilegierter Höhenlage",
        ort: "69469 Weinheim",
        image: "/images/referenzen/gal-villa-01-1600.jpg",
        bilder: [
          "/images/referenzen/gal-villa-01-1600.jpg",
          "/images/referenzen/gal-villa-02-1600.jpg",
          "/images/referenzen/gal-villa-03-1600.jpg",
          "/images/referenzen/gal-villa-04-1600.jpg",
          "/images/referenzen/gal-villa-05-1600.jpg",
          "/images/referenzen/gal-villa-06-1600.jpg",
          "/images/referenzen/gal-villa-07-1600.jpg",
          "/images/referenzen/gal-villa-08-1600.jpg",
          "/images/referenzen/gal-villa-09-1600.jpg",
          "/images/referenzen/gal-villa-10-1600.jpg",
          "/images/referenzen/gal-villa-11-1600.jpg",
          "/images/referenzen/gal-villa-12-1600.jpg",
          "/images/referenzen/gal-villa-13-1600.jpg",
          "/images/referenzen/gal-villa-14-1600.jpg",
        ],
        preis: "2.450.000 €",
        eckdaten: {
          wohnflaeche: "ca. 262 m²",
          grundstueck: "ca. 846 m²",
          nutzflaeche: "ca. 120 m²",
          zimmer: 8,
          schlafzimmer: 6,
          badezimmer: 3,
          balkonTerrasse: 1,
          stellplaetze: 4,
        },
        bauinfo: {
          baujahr: 2013,
          letzteModernisierung: 2013,
          zustand: "gepflegt",
          energieausweis: "Bedarfsausweis, Klasse C, 92,60 kWh/(m²·a), gültig bis 03.12.2035",
          primaerenergie: "Gas",
          heizung: "Gas-Heizung",
        },
        verfuegbar: "nach Vereinbarung",
        beschreibung: [
          "Großzügiges Villenanwesen in privilegierter Höhenlage mit Blick über die Rheinebene — Nähe Schlosspark und Altstadt. Diese Immobilie richtet sich nicht an Suchende, sondern an Menschen, die bewusst wählen.",
          "An Käufer, für die eine Lage mehr ist als eine Adresse, für die Weitblick nicht nur Aussicht bedeutet und Privatsphäre kein Luxus, sondern Voraussetzung ist.",
          "In einer der begehrtesten Wohnlagen Weinheims vereint dieses Anwesen architektonische Klarheit mit Großzügigkeit, einem hohen Maß an Privatsphäre und einer besonderen Lagequalität — ohne dabei auf die Nähe zur Stadt zu verzichten. Ein Zuhause für Menschen, die Qualität schätzen.",
          "Architektur & Raumgefühl: Die Architektur dieses Anwesens folgt keiner kurzlebigen Mode, sondern einer klaren, zeitlosen Linie. Harmonisch aufeinander abgestimmte Raumabfolgen, teilweise bodentiefe Fensterflächen und gezielt gesetzte Blickachsen schaffen ein offenes, lichtdurchflutetes Wohngefühl über mehrere Ebenen hinweg. Die Verbindung der Geschosse erfolgt über eine elegante Treppengestaltung, die nicht nur funktional ist, sondern zugleich als gestalterisches Element wirkt und dem Haus eine besondere innere Dynamik verleiht.",
          "Wohnen, Kochen & Zusammensein: Das Herz des Hauses bildet der großzügige Wohn- und Essbereich mit Kamin und direktem Zugang zur Terrasse. Hier entstehen fließende Übergänge zwischen Innen- und Außenraum, zwischen Alltag und Genuss, zwischen Rückzug und Geselligkeit. Die hochwertige Küche mit Markenausstattung ist offen integriert und wird zum selbstverständlichen Treffpunkt für Familie, Freunde und Gäste.",
          "Private Rückzugsbereiche: In den oberen Ebenen befinden sich die privaten Rückzugsräume des Hauses. Schlafzimmer, Bäder und Ankleidebereiche sind so angeordnet, dass sie Intimität bieten und gleichzeitig von Licht und Ausblick profitieren. Ein kleines Highlight ist das Dachgeschoss mit Wohn- und separatem Schlafbereich und Dachterrasse. Ein Rückzugsort für besondere Momente, Weitblick und persönliche Auszeiten.",
          "Gäste, Arbeiten & Einliegerwohnung: Ergänzt wird das Raumangebot durch eine gemütliche Einliegerwohnung, die vielseitige Nutzungsmöglichkeiten eröffnet. Ob als komfortabler Gästebereich, für erwachsene Kinder oder für repräsentatives Arbeiten von zuhause — die Einheit ist funktional klar gegliedert und dennoch harmonisch in das Gesamtkonzept des Anwesens eingebunden.",
          "Garten, Terrassen & Außenräume: Die Außenbereiche sind bewusst als Erweiterung des Wohnraums gestaltet. Die großzügige Terrasse eröffnet geschützte Aufenthaltsbereiche mit Blick ins Grüne. Der gewachsene Garten bietet ein hohes Maß an Privatsphäre und ist ein angenehmer Rückzugsort zu jeder Tageszeit. Trotz der ruhigen Lage bleiben Schlosspark, Altstadt und das urbane Leben Weinheims in kurzer Distanz erreichbar — eine ideale Verbindung aus Nähe und Rückzug.",
          "Komfort, Technik & Sicherheit: Hochwertige Ausstattungsdetails, moderne Gebäudetechnik sowie durchdachte Sicherheits- und Komfortelemente unterstreichen den Anspruch dieses Anwesens. Eine großzügige, abgeschlossene Doppelgarage mit komfortabler Zufahrt sowie zusätzliche Außenstellplätze stehen zur Verfügung — auch für hochwertige Fahrzeuge bestens geeignet. Die Immobilie überzeugt durch angenehmes, elegantes Wohnen auf hohem Niveau.",
        ],
        lage:
          "Die Villa liegt in einer der exklusivsten Wohngegenden Weinheims — geprägt von Privatsphäre und einem hochwertigen Wohnumfeld. Eingebettet in die idyllische Landschaft der Bergstraße genießen Sie hier Natur, Komfort, urbane Nähe sowie den Blick in die Rheinebene. Die charmante Weinheimer Altstadt mit ihrem historischen Marktplatz, Boutiquen, Cafés und Restaurants ist in wenigen Minuten erreichbar, ebenso wie Schulen, Kindergärten und vielfältige Freizeitmöglichkeiten. Dank der hervorragenden Verkehrsanbindung erreichen Sie Heidelberg und Mannheim in weniger als 20 Minuten, den Flughafen Frankfurt in rund 45 Minuten. Gleichzeitig laden Weinberge und der Odenwald direkt vor der Haustür zu Spaziergängen, Wanderungen oder sportlichen Aktivitäten ein. Eine Lage, die für hohe Lebensqualität und stilvolles Wohnen steht.",
        ausstattung: [
          "Balkon",
          "Luxus-Ausstattung",
          "Dusche",
          "Bad mit Badewanne",
          "Bad mit Fenster",
          "Einbauküche",
          "Fliesen",
          "Parkett",
          "Granit",
          "Kamin",
          "Klimatisiert",
          "Doppelgarage",
          "Garten",
          "Keller",
          "Abstellraum",
          "Gäste-WC",
        ],
      },
      {
        slug: "denkmal-mfh",
        titel: "Denkmalgeschütztes Mehrfamilienhaus mit Altstadtblick",
        untertitel: "Historischer Charme in zentraler Lage",
        ort: "69469 Weinheim",
        image: "/images/referenzen/gal-denkmal-01-1600.jpg",
        bilder: [
          "/images/referenzen/gal-denkmal-01-1600.jpg",
          "/images/referenzen/gal-denkmal-02-1600.jpg",
          "/images/referenzen/gal-denkmal-03-1600.jpg",
          "/images/referenzen/gal-denkmal-04-1600.jpg",
          "/images/referenzen/gal-denkmal-05-1600.jpg",
          "/images/referenzen/gal-denkmal-06-1600.jpg",
          "/images/referenzen/gal-denkmal-07-1600.jpg",
          "/images/referenzen/gal-denkmal-08-1600.jpg",
          "/images/referenzen/gal-denkmal-09-1600.jpg",
        ],
        preis: "1.300.000 €",
        eckdaten: {
          wohnflaeche: "ca. 280 m²",
          grundstueck: "ca. 650 m²",
          zimmer: 12,
          badezimmer: 3,
          balkonTerrasse: 1,
        },
        bauinfo: {
          baujahr: 1906,
          letzteModernisierung: 2024,
          zustand: "renoviert",
          energieausweis: "nicht erforderlich (Denkmalschutz gemäß § 79 Abs. 4 GEG)",
          primaerenergie: "Gas",
          heizung: "Zentralheizung",
          denkmalgeschuetzt: true,
        },
        verfuegbar: "nach Vereinbarung",
        beschreibung: [
          "Weinheim | Zentrale Lage mit Blick auf die Altstadt. Die denkmalgeschützte Liegenschaft vereint historische Substanz, eine gefragte Lage in Weinheim sowie einen freien Blick über die Altstadt zu einem seltenen Gesamtangebot.",
          "Das um ca. 1906 errichtete Anwesen wurde über die Jahre behutsam weiterentwickelt und bietet heute vielseitige Nutzungsmöglichkeiten — von der Mehrgenerationennutzung bis hin zu einer langfristig orientierten Kapitalanlage. Im Jahr 2024 wurde das Dach der Immobilie umfassend saniert, was einen wichtigen Beitrag zum langfristigen Werterhalt leistet.",
          "Die leicht erhöhte Position unterstreicht den besonderen Charakter der Immobilie und schafft in Verbindung mit der Privatstraße für Anlieger ein angenehmes Maß an Privatsphäre.",
          "Wohnungsaufteilung & Ausstattung: Die Gesamtwohnfläche von ca. 280 m² verteilt sich auf drei Wohneinheiten. Die Wohnungen im Erdgeschoss sowie im Obergeschoss verfügen jeweils über eine klassische Raumaufteilung mit 4 Zimmern, Küche und Bad sowie sonnigem Balkon. Die Erdgeschosswohnung bietet zusätzlich einen Innenhof mit kleiner Terrasse und Zugang zum Garten. Die Wohnung im Obergeschoss hat direkten Zugang zum idyllisch angelegten Garten. Weitere Zugänge zu den übrigen Gartenbereichen sind sowohl von außen als auch über das Treppenhaus möglich. Aktuell ist jeder Wohnung ein eigener Gartenbereich zugeordnet. Die Dachgeschosswohnung ergänzt das Ensemble als eigenständige Einheit und verfügt ebenfalls über 4 Zimmer, Küche und Bad. Alle Wohnungen sind mit hochwertigen Pitch-Pine-Dielenböden ausgestattet, die den historischen Charakter der Immobilie eindrucksvoll unterstreichen.",
          "Daten & Perspektiven für Kapitalanleger: Dem Investor stehen aktuell drei Wohneinheiten mit insgesamt ca. 280 m² Wohnfläche sowie ein Grundstück von ca. 650 m² zur Verfügung (Angaben gemäß Eigentümer). Aktuelle Mietsituation: Erdgeschosswohnung ca. 1.070 €/Monat, Obergeschosswohnung ca. 1.045 €/Monat, Dachgeschosswohnung ca. 1.050 €/Monat. Gesamt: ca. 3.165 €/Monat bzw. 37.980 € p.a. Dies entspricht einer Bruttorendite von ca. 2,9 % bezogen auf den Angebotspreis. Die Immobilie bietet damit eine solide vermietete Ausgangssituation in gefragter Lage.",
          "Denkmalschutz & Perspektive: Die Immobilie steht unter Denkmalschutz (Außenhülle). Hieraus können sich — insbesondere im Rahmen von Sanierungsmaßnahmen — steuerliche Vorteile gemäß § 7i EStG ergeben. Der rückwärtige Anbau ist nicht denkmalgeschützt und eröffnet dadurch zusätzliche gestalterische und bauliche Flexibilität. Ein Energieausweis ist aufgrund der Denkmaleigenschaft der Immobilie gemäß § 79 Abs. 4 GEG nicht erforderlich. Die Kombination aus Lage, Substanz und Nutzungsperspektive macht dieses Objekt zu einer seltenen Gelegenheit in Weinheim.",
        ],
        lage:
          "Die Immobilie befindet sich in begehrter Lage Weinheims — in unmittelbarer Nähe zur historischen Altstadt. Die gewachsene Wohnlage verbindet zentrale Erreichbarkeit mit den Vorteilen urbanen Wohnens. Durch die leicht erhöhte Position eröffnet sich ein attraktiver Blick auf die Altstadt sowie in die umliegende Umgebung. Der charmante Marktplatz mit seinen Cafés und Restaurants ist ebenso wie der Schlosspark und der weitläufige Exotenwald in wenigen Minuten erreichbar — ideal für Spaziergänge, sportliche Aktivitäten oder entspannte Stunden im Grünen. Die Anbindung an den öffentlichen Nahverkehr ist sehr gut: Eine Straßenbahnhaltestelle sowie Busverbindungen befinden sich in fußläufiger Entfernung und ermöglichen eine schnelle Erreichbarkeit der umliegenden Städte. Auch die überregionale Verkehrsanbindung ist hervorragend. Die Autobahnen A5 und A659 sind in kurzer Zeit erreichbar und bieten eine direkte Verbindung in die Metropolregion Rhein-Neckar mit den Städten Heidelberg, Mannheim und Darmstadt. Weinheim zählt zu den gefragtesten Wohnorten an der Bergstraße und überzeugt durch eine hohe Lebensqualität, eine ausgezeichnete Infrastruktur sowie die Nähe zu bedeutenden Wirtschaftsstandorten.",
        ausstattung: [
          "Balkon",
          "Standard-Ausstattung",
          "Dusche",
          "Bad mit Badewanne",
          "Bad mit Fenster",
          "Fliesen",
          "Pitch-Pine-Parkett",
          "Keller",
          "Abstellraum",
          "Denkmalgeschützt (Außenhülle)",
        ],
      },
      {
        slug: "familien-efh",
        titel: "Familienglück in gemütlichem Einfamilienhaus",
        untertitel: "EFH in guter Lage — Bretten",
        ort: "75015 Bretten",
        image: "/images/referenzen/gal-familien-01-1600.jpg",
        bilder: [
          "/images/referenzen/gal-familien-01-1600.jpg",
          "/images/referenzen/gal-familien-02-1600.jpg",
          "/images/referenzen/gal-familien-03-1600.jpg",
          "/images/referenzen/gal-familien-04-1600.jpg",
          "/images/referenzen/gal-familien-05-1600.jpg",
          "/images/referenzen/gal-familien-06-1600.jpg",
          "/images/referenzen/gal-familien-07-1600.jpg",
          "/images/referenzen/gal-familien-08-1600.jpg",
          "/images/referenzen/gal-familien-09-1600.jpg",
          "/images/referenzen/gal-familien-10-1600.jpg",
          "/images/referenzen/gal-familien-11-1600.jpg",
          "/images/referenzen/gal-familien-12-1600.jpg",
          "/images/referenzen/gal-familien-13-1600.jpg",
          "/images/referenzen/gal-familien-14-1600.jpg",
          "/images/referenzen/gal-familien-15-1600.jpg",
        ],
        preis: "695.000 €",
        eckdaten: {
          wohnflaeche: "ca. 216 m²",
          grundstueck: "ca. 695 m²",
          zimmer: 7,
          badezimmer: 3,
          balkonTerrasse: 1,
          balkonFlaeche: "ca. 30 m²",
          stellplaetze: 2,
        },
        bauinfo: {
          baujahr: 1982,
          letzteModernisierung: 2020,
          zustand: "gepflegt",
          energieausweis: "Verbrauchsausweis, Klasse F, 170,80 kWh/(m²·a), gültig bis 05.02.2036",
          primaerenergie: "Gas",
          heizung: "Gas-Heizung",
          warmwasser: true,
        },
        verfuegbar: "nach Vereinbarung",
        beschreibung: [
          "Es erwartet Sie ein großzügiges und attraktives Einfamilienhaus mit Einliegerwohnung, das viel Raum für die ganze Familie bietet. Durch die separate Einliegerwohnung ist ausreichend Platz für Großeltern, ein Kindermädchen oder Gäste vorhanden. Dank des eigenen Eingangs und der sonnigen Terrasse eignet sich dieser Bereich auch hervorragend zur Vermietung.",
          "Erdgeschoss: Ein großzügiges Entrée mit Garderobe bildet den einladenden Eingangsbereich. Die Einbauküche verfügt über einen separaten Vorratsraum. Außerdem befinden sich auf dieser Ebene ein Gäste-WC, ein offener Essbereich sowie der angeschlossene, geschmackvoll gestaltete Wohnbereich mit Zugang zur Terrasse und dem idyllischen Garten. Der Kamin mit individuell gemauerter Sitzecke sowie ein weiterer Kaminofen sorgen für eine besonders gemütliche Atmosphäre. Vom Wohnzimmer aus gelangen Sie auf die sonnige Terrasse mit Kamin und Heizstrahler — ein idealer Ort zum Grillen, Feiern und Entspannen. Der liebevoll angelegte Garten mit Teich und Wasserlauf bietet mehrere Rückzugs- und Ruheoasen. Zudem befindet sich im Erdgeschoss ein Gäste- oder Büroraum.",
          "Obergeschoss: Das Obergeschoss überzeugt durch eine offene Galerie mit Blick in den Wohnbereich. Auf dieser Etage befinden sich vier Schlafzimmer sowie ein großes Tageslichtbad.",
          "Untergeschoss: Im Untergeschoss erwartet Sie eine kleine Wellness-Oase mit Sauna, Ruheraum und Bad. Darüber hinaus stehen ein Hobbyraum, ein Vorratsraum sowie der Heizungsraum und weitere Nutzflächen zur Verfügung.",
          "Eine Doppelgarage sowie zwei zusätzliche Außenstellplätze runden dieses attraktive Angebot ab. Die Immobilie präsentiert sich in einem sehr gepflegten Zustand und eignet sich ideal für eine Familie, die Wert auf viel Platz, Ruhe und eine ansprechende, gefragte Wohnlage legt.",
        ],
        lage:
          "Die Immobilie liegt im beliebten Ortsteil Gölshausen-Bretten in einer ruhigen, gewachsenen Wohnlage mit überwiegend Ein- und Zweifamilienhäusern. Einkaufsmöglichkeiten, Kindergarten, Schule, Bushaltestelle sowie Ärzte sind im nahen Umfeld vorhanden. Die Brettener Innenstadt ist in wenigen Autominuten erreichbar. Eine gute Verkehrsanbindung in Richtung Karlsruhe, Bruchsal und Stuttgart rundet die Lage ab.",
        ausstattung: [
          "Balkon",
          "Einzelgarage",
          "Standard-Ausstattung",
          "Dusche",
          "Bad mit Badewanne",
          "Bad mit Fenster",
          "Einbauküche",
          "Fliesen",
          "Kamin",
          "Sauna",
          "Keller",
          "Gäste-WC",
        ],
      },
      {
        slug: "toplage-villa",
        titel: "Top-Secret in Toplage — Villa im Rhein-Neckar-Raum",
        untertitel: "Villa sucht neuen Besitzer — diskretes Angebot auf Anfrage",
        ort: "Rhein-Neckar-Raum",
        image: null,
        preis: "auf Anfrage",
        eckdaten: {
          wohnflaeche: "ca. 240 m²",
          grundstueck: "ca. 1.800 m²",
          schlafzimmer: 3,
          badezimmer: 2,
          balkonTerrasse: 1,
          stellplaetze: 2,
        },
        bauinfo: {
          baujahr: 1897,
          letzteModernisierung: 2017,
          zustand: "renoviert",
          energieausweis: "nicht erforderlich (Denkmalschutz)",
          primaerenergie: "Öl",
          heizung: "Öl-Heizung",
          denkmalgeschuetzt: true,
        },
        verfuegbar: "nach Vereinbarung",
        beschreibung: [
          "Besondere Immobilien verlangen eine besondere Präsentation — und manchmal auch einen stillen Auftritt. Aus Rücksicht auf die Privatsphäre der Eigentümer wurde dieses außergewöhnliche Anwesen diskret angeboten. Die genaue Lage sowie Innenansichten erhalten Sie daher ausschließlich auf Anfrage — und nur im persönlichen Kontakt.",
          "Was wir Ihnen verraten dürfen: Zur Vermarktung steht eine Villa, die Geschichte und Moderne auf beeindruckende Weise vereint. Das repräsentative Anwesen aus dem Jahr 1897 wurde zuletzt 2017 teilmodernisiert und präsentiert sich heute als stilvolles Domizil für gehobene Ansprüche.",
          "Auf rund 240 m² Wohnfläche erwartet Sie ein großzügiges Raumkonzept mit imposanter Eingangshalle, lichtdurchflutetem Wohn-/Essbereich mit offenem Kamin und Zugang zum 2-stöckigen Wintergarten, sowie eine geschmackvolle Landhausküche. Im Obergeschoss befinden sich zwei Schlafzimmer mit Ankleide, sowie ein luxuriöses Tageslichtbad und ein Gästebad. Das Dachgeschoss bietet zusätzliche Rückzugsmöglichkeiten.",
          "Das Untergeschoss ist aufgeteilt in Studio/Büro, Weinkeller, Hauswirtschaftsraum und einen weiteren Zugang zum Wintergarten, über den sich der parkähnliche Garten erschließt. Das etwa 1.800 m² große Grundstück ist eine Seltenheit: eine grüne Oase, die Privatsphäre und Inspiration gleichermaßen schenkt.",
        ],
        lage:
          "Die Villa befindet sich in einer der begehrtesten Lagen der Rhein-Neckar-Region mit Blick auf den Neckar. Nur wenige Schritte trennen Sie von einer malerischen Altstadt mit ihren historischen Gassen, Cafés und Restaurants, Schulen, Kindergärten, Ärzten, Einkaufsmöglichkeiten und Sportangeboten. Eine ausgezeichnete Verkehrsanbindung an die Universitätsstädte Heidelberg und Mannheim mit Pkw oder öffentlichen Verkehrsmitteln rundet die Lage ab.",
        ausstattung: [
          "Balkon",
          "Gehobene Ausstattung",
          "Dusche",
          "Bad mit Badewanne",
          "Bad mit Fenster",
          "Einbauküche",
          "Fliesen",
          "Stein",
          "Parkett",
          "Kamin",
          "Garage",
          "Parken im Freien",
          "Garten",
          "Wintergarten",
          "Keller",
          "Gäste-WC",
          "Denkmalgeschützt",
        ],
      },
    ],
  },
  // Echte verkaufte/vermittelte Referenzobjekte (Quelle: Änderungsdokument 11.06.2026).
  // Birkenau und Weinheim-West folgen, sobald Edith die Angaben nachliefert.
  referenzen: {
    eyebrow: "Referenzen",
    headline: "Erfolgreich vermittelt.",
    intro:
      "Eine Auswahl bereits verkaufter oder vermittelter Immobilien. Aus Diskretionsgründen nenne ich weitere Details ausschließlich im persönlichen Gespräch.",
    items: [
      { slug: "ref-edenkoben-villa", titel: "Juwel in der Südpfalz", ort: "Edenkoben, Südpfalz", image: "/images/referenzen/ref-edenkoben-villa-1600.jpg", badge: "Verkauft", meta: ["Villa", "ca. 240 m² Wohnfläche", "ca. 730 m² Grundstück", "6 Zimmer"] },
      { slug: "ref-hockenheim-wohnung", titel: "Gemütliche Wohnoase in zentraler Lage", ort: "Hockenheim", image: "/images/referenzen/ref-hockenheim-wohnung-1600.jpg", badge: "Verkauft", meta: ["Etagenwohnung", "ca. 62 m² Wohnfläche", "2 Zimmer"] },
      { slug: "ref-rheingoenheim-dg", titel: "Sonnige Dachgeschosswohnung", ort: "Ludwigshafen-Rheingönheim", image: "/images/referenzen/ref-rheingoenheim-dg-1600.jpg", badge: "Verkauft", meta: ["Wohnung", "ca. 78 m² Wohnfläche", "2,5 Zimmer"] },
      { slug: "ref-weinheim-weststadt", titel: "Attraktive, sonnige Wohnung", ort: "Weinheim-Weststadt", image: "/images/referenzen/ref-weinheim-weststadt-1600.jpg", badge: "Vermietet", meta: ["Wohnung", "ca. 65 m² Wohnfläche", "2 Zimmer"] },
      { slug: "ref-mainz-wohnung", titel: "Attraktive, sonnige 2-Zimmer-Wohnung", ort: "Mainz", image: "/images/referenzen/ref-mainz-wohnung-1600.jpg", badge: "Vermietet", meta: ["Wohnung", "ca. 64 m² Wohnfläche", "2 Zimmer"] },
      { slug: "ref-weinheim-musikerviertel", titel: "Sonniges Einfamilienhaus mit Blick in die Rheinebene", ort: "Weinheim-Musikerviertel", image: "/images/referenzen/ref-weinheim-musikerviertel-1600.jpg", badge: "Verkauft", meta: ["Einfamilienhaus", "ca. 188 m² Wohnfläche", "ca. 735 m² Grundstück", "6 Zimmer"] },
      { slug: "ref-weinheim-villa", titel: "Repräsentative Villa in beneidenswerter Lage", ort: "Weinheim", image: "/images/referenzen/ref-weinheim-villa-1600.jpg", badge: "Verkauft", meta: ["Villa", "ca. 600 m² Wohnfläche", "ca. 2.227 m² Grundstück", "13 Zimmer"] },
      { slug: "ref-gorxheimertal", titel: "Außergewöhnliches Kleinod", ort: "Gorxheimertal", image: "/images/referenzen/ref-gorxheimertal-1600.jpg", badge: "Verkauft", meta: ["Einfamilienhaus", "ca. 170 m² Wohnfläche", "ca. 567 m² Grundstück", "8 Zimmer"] },
      { slug: "ref-weinheim-sulzbach", titel: "Französisches Flair, ganz nah", ort: "Weinheim-Sulzbach", image: "/images/referenzen/ref-weinheim-sulzbach-1600.jpg", badge: "Verkauft", meta: ["Einfamilienhaus", "ca. 117 m² Wohnfläche", "ca. 204 m² Grundstück", "4 Zimmer"] },
      { slug: "ref-weinheim-stadthaus", titel: "Beeindruckendes Stadthaus in gesuchter Lage", ort: "Weinheim, Fußgängerzone", image: "/images/referenzen/ref-weinheim-stadthaus-1600.jpg", badge: "Verkauft", meta: ["Mehrfamilienhaus", "ca. 396 m² Wohnfläche", "ca. 274 m² Grundstück", "11 Zimmer"] },
      { slug: "ref-weinheim-zweifamilien", titel: "Großzügiges Zweifamilienhaus", ort: "Weinheim", image: "/images/referenzen/ref-weinheim-zweifamilien-1600.jpg", badge: "Verkauft", meta: ["Mehrfamilienhaus", "ca. 330 m² Wohnfläche", "ca. 800 m² Grundstück", "8 Zimmer"] },
      { slug: "ref-heddesheim-doppelhaus", titel: "Gemütliches Doppelhaus", ort: "Heddesheim", image: "/images/referenzen/ref-heddesheim-doppelhaus-1600.jpg", badge: "Verkauft", meta: ["Mehrfamilienhaus", "ca. 140 m² Wohnfläche", "ca. 369 m² Grundstück", "5 Zimmer"] },
      { slug: "ref-weinheim-mfh", titel: "Charmantes Mehrfamilienhaus", ort: "Weinheim", image: "/images/referenzen/ref-weinheim-mfh-1600.jpg", badge: "Verkauft", meta: ["Mehrfamilienhaus", "ca. 425 m² Wohnfläche", "ca. 365 m² Grundstück", "15 Zimmer"] },
    ],
  },
  homeStaging: {
    eyebrow: "Home Staging",
    headline: "Weil Ihre Immobilie es wert ist.",
    body:
      "Ein stimmungsvoll inszenierter Raum spricht nicht nur den Verstand an — sondern das Herz. Bei Bedarf vermittle ich Home Staging, klassisch vor Ort oder digital. Gerade leerstehende oder schwer verkäufliche Immobilien gewinnen so an Wärme, Charakter und Vorstellungskraft.",
    image: {
      src: "/images/home-staging-original-1600.jpg",
      alt: "Stilvoll inszenierter Esszimmer-Raum mit Designerstühlen und Kunstwerk — Beispiel für die Wirkung von Home Staging",
    },
  },
  presse: {
    eyebrow: "Aus der Presse",
    headline: "„Verkaufen aus Leidenschaft!“",
    zitat:
      "Unter dem Titel „Die Philosophie lautet: Verkaufen aus Leidenschaft!“ wurde Edith Voß und ihre Haltung zum Maklerberuf in einem regionalen Zeitungsbeitrag vorgestellt.",
    images: [
      {
        src: "/images/presse-verkaufen-aus-leidenschaft-1600.jpg",
        alt: "Zeitungsartikel über Edith Voß: „Die Philosophie lautet: Verkaufen aus Leidenschaft!“",
      },
    ],
  },
  region: {
    headline: "Regional verwurzelt — überregional erfolgreich.",
    body: "Mein Tätigkeitsgebiet umfasst die Rhein-Neckar-Region mit Weinheim, Karlsruhe und Umgebung, den vorderen Odenwald und Rheinland-Pfalz, auf Anfrage auch darüber hinaus.",
    orte: ["Weinheim", "Mannheim", "Heidelberg", "Karlsruhe", "Frankfurt", "Bergstraße", "Ilvesheim", "Vorderer Odenwald", "Rheinland-Pfalz"],
  },
  erfolgsschluessel: {
    eyebrow: "Mein Schlüssel zum Erfolg",
    headline: "Die Kombination macht den Unterschied.",
    body: "Fairness, Fachwissen, fundierte persönliche Betreuung und Beratung — sowie kompetente Unterstützung von Käufer und Kaufinteressenten.",
    items: [
      { nr: "01", title: "Fairness" },
      { nr: "02", title: "Fachwissen" },
      { nr: "03", title: "Persönliche Betreuung" },
      { nr: "04", title: "Kompetente Unterstützung" },
    ],
  },
  testimonial: {
    quote: "Einige meiner Kunden haben die Käufer erst anlässlich des Notartermins kennengelernt.",
    attribution: "Edith Voss",
  },
  // Echte, vom Kunden freigegebene Bewertungen (Quelle: Unterordner „Bewertungen", Stand 11.06.2026).
  kundenstimmen: {
    eyebrow: "Kundenstimmen",
    headline: "Was meine Kunden sagen",
    stimmen: [
      {
        quote:
          "Frau Voss ist seit vielen Jahren eine höchst kompetente, engagierte und empathische Immobilienmaklerin. Die Erstellung der Exposés, die Durchführung der Besichtigungen und die Vorbereitung bis zur Übergabe waren von Anfang bis Abschluss absolut professionell. Aufgrund ihres hervorragenden Netzwerks konnten die Objekte in kurzer Zeit erfolgreich und mit einem sehr guten Ergebnis vermarktet werden. Ich kann sie uneingeschränkt und wärmstens weiterempfehlen.",
        author: "Dr. Gerd Fischer, Weinheim",
      },
      {
        quote:
          "Wir haben Frau Voss mehrfach mit der Vermarktung und Vermittlung einiger Projekte beauftragt. Dank ihrer hervorragenden Marktkenntnisse, ihrem großen Netzwerk sowie der ansprechenden Präsentation der Objekte hat sie in kurzer Zeit die von uns gewünschten Abschlüsse zu unseren Preisvorstellungen erreicht. Ihre Kompetenz und Zuverlässigkeit hat uns sehr beeindruckt.",
        author: "Alfred Wimmer, Weinheim",
      },
      {
        quote:
          "Frau Edith Voss, die ich eines Tages in ihrem Büro aufsuchte, hat mich von da an sehr effizient in allen Immobilien betreffenden Fragen beraten. Ganz besonders effizient hat sie sich bei der Suche nach einem Objekt zum Kauf und anschließender Vermietung erwiesen. Überhaupt ist ihr besonderes Händchen im Umgang mit Kunden und ihre Menschenkenntnis, geschult durch jahrelange Erfahrung, mehr als bemerkenswert. Da verliert man keine Zeit und fühlt sich sofort gut aufgehoben. Beauftragt man sie mit etwas, das eine Immobilie betrifft, so hat man gleichzeitig ein „Rund-um-sorglos-Paket“ gebucht und kann sicher sein, dass sämtliche Optionen, die den Kunden weiterbringen, von ihr ausgelotet und mit sicherer Hand in die richtigen Bahnen gelenkt werden.",
        author: "Barbara Stüssel",
      },
    ],
    googleHinweis:
      "Verifizierte Bewertungen folgen hier, sobald das Google-Business-Profil von V.I.B. Voß Immobilien Beratung aktiv und gelistet ist.",
    profilUrl: "TODO_VON_EDITH", // TODO_VON_EDITH: URL zum Google-Business-Profil, sobald vorhanden
  },
  tippgeber: {
    eyebrow: "Tippgeber",
    headline: "Sie kennen jemanden, der verkaufen möchte?",
    body: "Wenn Sie mir einen Tipp zu einer Immobilie geben und es zum erfolgreichen Verkauf kommt, erhalten Sie eine Tippgeber-Prämie. Nach der notariellen Beurkundung und dem Provisionseingang überweise ich Ihnen umgehend die vereinbarte Provision.",
    steps: [
      {
        nr: "01",
        title: "Sie geben mir den Tipp",
        body: "Über mein Kontaktformular oder unverbindlich per Anruf.",
      },
      {
        nr: "02",
        title: "Ich prüfe das Objekt",
        body: "Ist die Immobilie noch nicht unter Vertrag bei einem anderen Maklerbüro, starte ich den Prozess.",
      },
      {
        nr: "03",
        title: "Bei Verkauf erhalten Sie Ihre Provision",
        body: "Nach der notariellen Beurkundung und dem Provisionseingang überweise ich Ihnen umgehend die vereinbarte Tippgeber-Prämie.",
      },
    ],
    staffelHinweis:
      "Provisionsstaffel (wird im Erstgespräch individuell bestätigt):",
    staffel: [
      { range: "bis 400.000 €", provision: "1.500 €" },
      { range: "ab 500.000 €", provision: "3.000 €" },
      { range: "ab 700.000 €", provision: "4.000 €" },
      { range: "ab 900.000 €", provision: "5.000 €" },
      { range: "ab 1.000.000 €", provision: "6.000 €" },
      { range: "ab 1.500.000 €", provision: "8.000 €" },
    ],
    bedingungen: [
      "Der Eigentümer muss mit der Weitergabe seiner Daten einverstanden sein.",
      "Ihre Angaben behandle ich absolut vertraulich.",
    ],
    cta: { label: "Objekt empfehlen", href: "#kontakt" },
  },
  cta: {
    headline: "Lassen Sie uns über Ihre Immobilie sprechen.",
    sub: "Persönlich. Diskret.",
    schluss: "Man lebt nur einmal — wir zeigen Ihnen wo.",
  },
} as const;
